server:
  port: 80

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://15.164.85.227:8761/eureka

spring:
  application:
    name: apigateway-service
  cloud:
    gateway:
      routes:
        - id: login
          uri: http://42meet.kro.kr:8080
          predicates:
            - Path=/login/**
            - Method=GET, POST, OPTIONS
          filters:
            - RemoveRequestHeader=Cookie
        - id: member-service
          uri: lb://MEMBER-SERVICE
          predicates:
            - Path=/member/**
            - Method=GET, POST, OPTIONS
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/member/(?<segment>.*), /$\{segment}
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin Origin Access-Control-Request-Method Access-Control-Request-Headers
        - id: reservation-service-register
          uri: lb://RESERVATION-SERVICE
          predicates:
            - Path=/reservation/register
            - Method=GET, POST, OPTIONS
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/reservation/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin Origin Access-Control-Request-Method Access-Control-Request-Headers
        - id: reservation-service-delete
          uri: lb://RESERVATION-SERVICE
          predicates:
            - Path=/reservation/delete
            - Method=GET, POST, OPTIONS
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/reservation/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin Origin Access-Control-Request-Method Access-Control-Request-Headers
        - id: reservation-service-mypage
          uri: lb://RESERVATION-SERVICE
          predicates:
            - Path=/reservation/mypage/**
            - Method=GET, POST, OPTIONS
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/reservation/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin Origin Access-Control-Request-Method Access-Control-Request-Headers
        - id: reservation-service
          uri: lb://RESERVATION-SERVICE
          predicates:
            - Path=/reservation/**
            - Method=GET, POST, OPTIONS
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/reservation/(?<segment>.*), /$\{segment}
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin Origin Access-Control-Request-Method Access-Control-Request-Headers
        - id: frontend-service
          uri: http://3.35.14.180
          predicates:
            - Path=/**
            - Method=GET, POST, OPTIONS

token:
  secret: sample

42meet:
  server:
    host: http://42meet.kro.kr
    login: http://42meet.kro.kr/login
    redirect: http://42meet.kro.kr/booking
    test: http://localhost:3000