server:
  port: 80

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://15.164.85.227:8761/eureka

spring:
  application:
    name: apigateway-service
  cloud:
    gateway:
      routes:
        - id: member-service
          uri: lb://MEMBER-SERVICE
          predicates:
            - Path=/member/**
            - Method=GET, POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/member/(?<segment>.*), /$\{segment}
        - id: reservation-service
          uri: lb://RESERVATION-SERVICE
          predicates:
            - Path=/reservation/**
            - Method=GET, POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/reservation/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter
        - id: frontend-service
          uri: http://3.35.14.180/login
          predicates:
            - Path=/meeting/**
            - Method=GET, POST

token:
  secret: sample